package com.example.demo;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "books")
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Book {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    private String isbn;
    
    private String title;
    
    private String author;
    
    @Column(columnDefinition = "TEXT")
    private String introduce;
    
    @ElementCollection
    @CollectionTable(name = "book_tags", joinColumns = @JoinColumn(name = "book_id"))
    @Column(name = "tag")
    private List<String> tags;
    
    @ManyToOne
    @JoinColumn(name = "category_id")
    private BookCategory category;
    
    // Constructors, getters, and setters are generated by Lombok.
}
